In [5]:
import pandas as pd
import numpy as np

from sklearn import preprocessing

In [6]:
iris_df=pd.read_csv('Iris.csv')
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
label_encoder = preprocessing.LabelEncoder()

In [9]:
iris_df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [10]:
iris_df['species'] = label_encoder.fit_transform(iris_df['species'])
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [11]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [12]:
iris_df['species'].unique()

array([0, 1, 2])

In [13]:
from sklearn import datasets
from sklearn.preprocessing import OneHotEncoder

In [14]:
iris_data = datasets.load_iris()

iris_data = pd.DataFrame(data=np.c_[iris_data['data'],iris_data['target']],
                        columns = iris_data['feature_names'] + ['target'])
y = iris_data.target.values

In [15]:
iris_data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [16]:
onehotencoder = OneHotEncoder(categories = 'auto')
y = onehotencoder.fit_transform(y.reshape(-1,1))
print(y.toarray())

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [17]:
pd.get_dummies(iris_data.target).head()

0.0  1.0  2.0
0    1    0    0
1    1    0    0
2    1    0    0
3    1    0    0
4    1    0    0

## Hashing

In [18]:
from sklearn.feature_extraction import FeatureHasher

In [19]:
game_df = pd.read_csv('vgsales.csv', encoding = 'utf-8')
game_df.head()

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [20]:
game_df.columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [21]:
game_df.shape

(16598, 11)

In [22]:
game_df[['Name','Platform','Year','Genre','Publisher']].iloc[1:7]

Name Platform    Year         Genre Publisher
1         Super Mario Bros.      NES  1985.0      Platform  Nintendo
2            Mario Kart Wii      Wii  2008.0        Racing  Nintendo
3         Wii Sports Resort      Wii  2009.0        Sports  Nintendo
4  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo
5                    Tetris       GB  1989.0        Puzzle  Nintendo
6     New Super Mario Bros.       DS  2006.0      Platform  Nintendo

In [23]:
u_genres = np.unique(game_df['Genre'])
print('Total game genres : ', len(u_genres))
print(u_genres)

Total game genres :  12
['Action' 'Adventure' 'Fighting' 'Misc' 'Platform' 'Puzzle' 'Racing'
 'Role-Playing' 'Shooter' 'Simulation' 'Sports' 'Strategy']


In [24]:
fh = FeatureHasher(n_features = 6, input_type = 'string')
hashed_features = fh.fit_transform(game_df['Genre'])
hashed_features = hashed_features.toarray()
new_game_df = pd.concat([game_df[['Name', 'Genre']], pd.DataFrame(hashed_features)], axis = 1)
new_game_df

Name         Genre    0  \
0                                            Wii Sports        Sports -2.0   
1                                     Super Mario Bros.      Platform  0.0   
2                                        Mario Kart Wii        Racing -1.0   
3                                     Wii Sports Resort        Sports -2.0   
4                              Pokemon Red/Pokemon Blue  Role-Playing -1.0   
...                                                 ...           ...  ...   
16593                Woody Woodpecker in Crazy Castle 5      Platform  0.0   
16594                     Men in Black II: Alien Escape       Shooter -1.0   
16595  SCORE International Baja 1000: The Official Game        Racing -1.0   
16596                                        Know How 2        Puzzle  0.0   
16597                                  Spirits & Spells      Platform  0.0   

         1    2    3    4    5  
0      2.0  0.0 -2.0  0.0  0.0  
1      2.0  2.0 -1.0  1.0  0.0  
2      0.0  0.0  0.0  0.0 -1.0  
3      2.0  0.0 -2.0  0.0  0.0  
4      1.0  2.0  0.0  1.0 -1.0  
...    ...  ...  ...  ...  ...  
16593  2.0  2.0 -1.0  1.0  0.0  
16594  4.0  0.0 -1.0  0.0 -1.0  
16595  0.0  0.0  0.0  0.0 -1.0  
16596  1.0  1.0 -2.0  1.0 -1.0  
16597  2.0  2.0 -1.0  1.0  0.0  

[16598 rows x 8 columns]

## Grouping Operations

In [25]:
import numpy as np
import pandas as pd
import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [26]:
df = pd.read_csv('dataset.csv')
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [27]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [28]:
df.shape

(1470, 35)

In [30]:
df.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSince

In [31]:
for i in df.columns:
    print (i, ':', df[i].value_counts())
    print (' _ '*40)
    print (' _ '*40)

Age : 35    78
34    77
36    69
31    69
29    68
32    61
30    60
33    58
38    58
40    57
37    50
27    48
28    48
42    46
39    42
45    41
41    40
26    39
44    33
46    33
43    32
50    30
25    26
24    26
49    24
47    24
55    22
51    19
53    19
48    19
54    18
52    18
22    16
56    14
23    14
58    14
21    13
20    11
59    10
19     9
18     8
60     5
57     4
Name: Age, dtype: int64
 _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _ 
 _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _ 
Attrition : No     1233
Yes     237
Name: Attrition, dtype: int64
 _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _ 
 _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _ 
BusinessTravel : Travel_Rarely   

In [42]:
for i in df.columns:
    print (i, ':', df[i].unique())
    print (' _ '*40)
    print (' _ '*40)

Age : [41 49 37 33 27 32 59 30 38 36 35 29 31 34 28 22 53 24 21 42 44 46 39 43
 50 26 48 55 45 56 23 51 40 54 58 20 25 19 57 52 47 18 60]
 _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _ 
 _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _ 
Attrition : ['Yes' 'No']
 _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _ 
 _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _ 
BusinessTravel : ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
 _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _ 
 _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _ 
DailyRate : [1102  279 1373 1392  591 1005 

In [43]:
df=df.drop(['Over18','EmployeeNumber', 'EmployeeCount','StandardHours'],axis = 1)

KeyError: "['Over18' 'EmployeeNumber' 'EmployeeCount' 'StandardHours'] not found in axis"

In [44]:
df.shape
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager',
       'TotalSatisfaction_mean'],
      dtype='object')

In [45]:
df[['RelationshipSatisfaction','JobSatisfaction', 'EnvironmentSatisfaction','JobInvolvement']]

RelationshipSatisfaction  JobSatisfaction  EnvironmentSatisfaction  \
0                            1                4                        2   
1                            4                2                        3   
2                            2                3                        4   
3                            3                3                        4   
4                            4                2                        1   
...                        ...              ...                      ...   
1465                         3                4                        3   
1466                         1                1                        4   
1467                         2                2                        2   
1468                         4                2                        4   
1469                         1                3                        2   

      JobInvolvement  
0                  3  
1                  2  
2                  2  
3                  3  
4                  3  
...              ...  
1465               4  
1466               2  
1467               4  
1468               2  
1469               4  

[1470 rows x 4 columns]

In [47]:
df['TotalSatisfaction_mean'] = (df['RelationshipSatisfaction']  
                                + df['EnvironmentSatisfaction'] 
                                + df['JobSatisfaction'] 
                                + df['JobInvolvement'] 
                                + df['WorkLifeBalance'])/5

def Satif(df) : 
    if  df['TotalSatisfaction_mean'] > 2.35 :
        return 1
    else : 
        return 0
    
    
df['Satif'] = df.apply(lambda df:Satif(df) ,axis = 1)
df['Satif']

0       0
1       1
2       1
3       1
4       1
       ..
1465    1
1466    0
1467    1
1468    1
1469    1
Name: Satif, Length: 1470, dtype: int64

In [54]:
df['TotalSatisfaction_mean'] = (df['RelationshipSatisfaction'] 
                                + df['EnvironmentSatisfaction'] 
                                + df['JobSatisfaction'] 
                                + df['JobInvolvement'] 
                                + df['WorkLifeBalance'])/5

In [56]:
def Satif(df) :
    if df['TotalSatisfaction_mean'] > 2.35 :
        return 1
    else :
        return 0

df['Satif'] = df.apply(lambda df:Satif(df), axis = 1)
df['Satif']

0       0
1       1
2       1
3       1
4       1
       ..
1465    1
1466    0
1467    1
1468    1
1469    1
Name: Satif, Length: 1470, dtype: int64

In [57]:
df.shape

(1470, 33)

In [58]:
df['JobSatif_mean'] = (df['JobSatisfaction'] + df['JobInvolvement']) / 2

In [59]:
df.shape

(1470, 34)

In [60]:
def MovingPeople(df) :
    if df['NumCompaniesWorked'] > 4:
        return 1
    else :
        return 0
    df['MovingPeople'] = df.apply(lambda df:MovingPeople(df), axis = 1)
    df['MovingPeople']

In [61]:
df.shape

(1470, 34)

In [62]:
def LongDis(df):
    if df['DistanceFromHome'] > 11:
        return 1
    else :
        return 0
df['LongDis'] = df.apply(lambda df:LongDis(df), axis=1)
df['LongDis']

0       0
1       0
2       0
3       0
4       0
       ..
1465    1
1466    0
1467    0
1468    0
1469    0
Name: LongDis, Length: 1470, dtype: int64

In [63]:
def MiddleTraining(df):
    if df['TrainingTimesLastYear'] >= 3 and df['TrainingTimesLastYear'] <= 6:
        return 1
    else :
        return 0
df['MiddleTraining'] = df.apply(lambda df:MiddleTraining(df), axis=1)
df['MiddleTraining']

0       0
1       1
2       1
3       1
4       1
       ..
1465    1
1466    1
1467    0
1468    1
1469    1
Name: MiddleTraining, Length: 1470, dtype: int64

In [64]:
df['Time_in_each_comp'] = (df['Age'] - 20)/((df)['NumCompaniesWorked'] + 1)
df['Time_in_each_comp']

0        2.333333
1       14.500000
2        2.428571
3        6.500000
4        0.700000
          ...    
1465     3.200000
1466     3.800000
1467     3.500000
1468     9.666667
1469     4.666667
Name: Time_in_each_comp, Length: 1470, dtype: float64

In [65]:
df.shape

(1470, 37)

In [66]:
numeric_df = df.select_dtypes(include = [np.number])

categoric_df = df.select_dtypes(exclude = [np.number])

In [68]:
numericcol = numeric_df.columns.tolist()
categorycol =  categoric_df.columns.tolist()

print('Category :', categorycol)
print('\n Numeric :', numericcol)

Category : ['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']

 Numeric : ['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager', 'TotalSatisfaction_mean', 'Satif', 'JobSatif_mean', 'LongDis', 'MiddleTraining', 'Time_in_each_comp']


In [69]:
df=df.drop(['DailyRate', 'DistanceFromHome', 'EnvironmentSatisfaction',
            'HourlyRate', 'JobInvolvement',  
            'JobSatisfaction',  'NumCompaniesWorked', 
            'RelationshipSatisfaction', 'TrainingTimesLastYear'],axis=1)

In [70]:
df.shape

(1470, 28)

In [71]:
data = pd.get_dummies(df, columns=categorycol, drop_first=True)
print(data.columns)
print(data.shape)

Index(['Age', 'Education', 'JobLevel', 'MonthlyIncome', 'MonthlyRate',
       'PercentSalaryHike', 'PerformanceRating', 'StockOptionLevel',
       'TotalWorkingYears', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager',
       'TotalSatisfaction_mean', 'Satif', 'JobSatif_mean', 'LongDis',
       'MiddleTraining', 'Time_in_each_comp', 'Attrition_Yes',
       'BusinessTravel_Travel_Frequently', 'BusinessTravel_Travel_Rarely',
       'Department_Research & Development', 'Department_Sales',
       'EducationField_Life Sciences', 'EducationField_Marketing',
       'EducationField_Medical', 'EducationField_Other',
       'EducationField_Technical Degree', 'Gender_Male',
       'JobRole_Human Resources', 'JobRole_Laboratory Technician',
       'JobRole_Manager', 'JobRole_Manufacturing Director',
       'JobRole_Research Director', 'JobRole_Research Scientist',
       'JobRole_Sales Executive', 'JobRole_Sales Representative',
   

In [72]:
data.head()

Age  Education  JobLevel  MonthlyIncome  MonthlyRate  PercentSalaryHike  \
0   41          2         2           5993        19479                 11   
1   49          1         2           5130        24907                 23   
2   37          2         1           2090         2396                 15   
3   33          4         1           2909        23159                 11   
4   27          1         1           3468        16632                 12   

   PerformanceRating  StockOptionLevel  TotalWorkingYears  WorkLifeBalance  \
0                  3                 0                  8                1   
1                  4                 1                 10                3   
2                  3                 0                  7                3   
3                  3                 0                  8                3   
4                  3                 1                  6                3   

   ...  JobRole_Laboratory Technician  JobRole_Manager  \
0  ...                              0                0   
1  ...                              0                0   
2  ...                              1                0   
3  ...                              0                0   
4  ...                              1                0   

   JobRole_Manufacturing Director  JobRole_Research Director  \
0                               0                          0   
1                               0                          0   
2                               0                          0   
3                               0                          0   
4                               0                          0   

   JobRole_Research Scientist  JobRole_Sales Executive  \
0                           0                        1   
1                           1                        0   
2                           0                        0   
3                           1                        0   
4                           0                        0   

   JobRole_Sales Representative  MaritalStatus_Married  MaritalStatus_Single  \
0                             0                      0                     1   
1                             0                      1                     0   
2                             0                      0                     1   
3                             0                      1                     0   
4                             0                      1                     0   

   OverTime_Yes  
0             1  
1             0  
2             1  
3             1  
4             0  

[5 rows x 42 columns]