# Lists

In [466]:
L1=[1,2,3,5,6,8,10]

In [343]:
L1

[1, 2, 3, 5, 6, 8, 10]

In [344]:
L1[1]

2

In [345]:
L1[2:4]

[3, 5]

In [346]:
L1

[1, 2, 3, 5, 6, 8, 10]

In [347]:
L1.append(11)

In [348]:
L1

[1, 2, 3, 5, 6, 8, 10, 11]

In [349]:
L1.append([12,13])

In [350]:
L1

[1, 2, 3, 5, 6, 8, 10, 11, [12, 13]]

In [351]:
L1.extend([14,15])

In [352]:
L1

[1, 2, 3, 5, 6, 8, 10, 11, [12, 13], 14, 15]

In [353]:
L1.insert(3,4)

In [354]:
L1

[1, 2, 3, 4, 5, 6, 8, 10, 11, [12, 13], 14, 15]

In [355]:
L1.insert(7,9)

In [356]:
L1

[1, 2, 3, 4, 5, 6, 8, 9, 10, 11, [12, 13], 14, 15]

In [357]:
L1.pop(3)

4

In [358]:
L1

[1, 2, 3, 5, 6, 8, 9, 10, 11, [12, 13], 14, 15]

In [359]:
 L1.remove(5)

In [360]:
L1

[1, 2, 3, 6, 8, 9, 10, 11, [12, 13], 14, 15]

In [361]:
L1.insert(3,5)

In [362]:
L1.insert(3,5)

In [363]:
L1

[1, 2, 3, 5, 5, 6, 8, 9, 10, 11, [12, 13], 14, 15]

In [364]:
L1.remove(5)

# 

In [365]:
L1

[1, 2, 3, 5, 6, 8, 9, 10, 11, [12, 13], 14, 15]

In [366]:
L1.insert(5,5)

In [367]:
L1

[1, 2, 3, 5, 6, 5, 8, 9, 10, 11, [12, 13], 14, 15]

In [368]:
L1.remove(5)

In [369]:
L1

[1, 2, 3, 6, 5, 8, 9, 10, 11, [12, 13], 14, 15]

# Dictionary

In [371]:
dict1={'xx':10,'yy':20,'zz':30}

In [372]:
dict1

{'xx': 10, 'yy': 20, 'zz': 30}

In [373]:
type(dict1)

dict

In [374]:
dict2={'10':'aa','20':30}

In [375]:
dict2

{'10': 'aa', '20': 30}

In [376]:
dict1.keys()

dict_keys(['xx', 'yy', 'zz'])

In [377]:
dict1['xx']

10

In [378]:
dict1['yy']

20

In [379]:
dict1.values()

dict_values([10, 20, 30])

In [380]:
dict1.update({'ll':25,'kk':60})

In [381]:
dict1

{'xx': 10, 'yy': 20, 'zz': 30, 'll': 25, 'kk': 60}

In [382]:
dict1.clear()

In [383]:
dict1

{}

In [384]:
dict2.pop('10')

'aa'

In [385]:
dict2

{'20': 30}

In [386]:
#tuple

In [387]:
t=(10,20,30,40,'xx')

In [388]:
t

(10, 20, 30, 40, 'xx')

In [389]:
type(t)

tuple

In [390]:
t[1]

20

In [391]:
len(t)

5

In [392]:
t1=(100,10,20,8,50)

In [393]:
max(t1)

100

# Set

In [395]:
s1=set(t1)

In [396]:
s1

{8, 10, 20, 50, 100}

In [397]:
type(s1)

set

In [398]:
s1.add(88)

In [399]:
s1

{8, 10, 20, 50, 88, 100}

In [400]:
t2=tuple(s1)

In [401]:
t2

(100, 8, 10, 50, 20, 88)

In [402]:
s1=set(['xx','yy','zz'])

In [403]:
s2=set(['xx','yy','zz','ll'])

In [404]:
s1

{'xx', 'yy', 'zz'}

In [405]:
s2

{'ll', 'xx', 'yy', 'zz'}

In [406]:
s1.intersection(s2)

{'xx', 'yy', 'zz'}

In [407]:
s1.union(s2)

{'ll', 'xx', 'yy', 'zz'}

In [408]:
s1

{'xx', 'yy', 'zz'}

In [409]:
s1.difference(s2)

set()

In [410]:
s2.difference(s1)

{'ll'}

In [411]:
s1.issubset(s1)

True

In [412]:
s2.issubset(s2)

True

In [413]:
s2.issuperset(s1)

True

In [414]:
s1.issuperset(s2)

False

# NUMPY

In [415]:
#numpy

In [416]:
import numpy as np

In [417]:
ar1=np.array([3,33,333])

In [418]:
ar1

array([  3,  33, 333])

In [419]:
ar1[0]

3

In [420]:
ar1[2]

333

In [421]:
ar1[0]=5

In [422]:
ar1

array([  5,  33, 333])

In [423]:
ar2=np.array([[5,55,555],[6,66,666]]) #rank 2 array

In [424]:
ar2

array([[  5,  55, 555],
       [  6,  66, 666]])

In [425]:
ar2[1]

array([  6,  66, 666])

In [426]:
ar2[1][1]

66

In [427]:
a1=np.zeros([2,2])

In [428]:
a1

array([[0., 0.],
       [0., 0.]])

In [429]:
a2=np.ones([2,2], dtype=np.int64)

In [430]:
a3=np.full([2,2],8)

In [431]:
a3

array([[8, 8],
       [8, 8]])

In [432]:
a4=np.eye(4,4)

In [433]:
a4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [434]:
a5=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [435]:
a5

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [436]:
a5.shape

(3, 3)

In [437]:
a5[1:2]

array([[40, 50, 60]])

In [438]:
a5[1:3]

array([[40, 50, 60],
       [70, 80, 90]])

In [439]:
a5[0:3]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [440]:
a5[1:,]

array([[40, 50, 60],
       [70, 80, 90]])

In [441]:
a5[0:,]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [442]:
a5[:,1]

array([20, 50, 80])

In [443]:
a5[:,2]

array([30, 60, 90])

In [444]:
a5

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [445]:
filter1=(a5>40)

In [446]:
filter1

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [447]:
a5[filter1]

array([50, 60, 70, 80, 90])

In [448]:
d=np.array([10.52,50.6],dtype=np.int64)

In [449]:
d

array([10, 50], dtype=int64)

In [450]:
x=np.array([[11,12],[15,16]])

In [451]:
y=np.array([[55,66],[99,88]])

In [452]:
z=np.add(x,y)

In [453]:
z

array([[ 66,  78],
       [114, 104]])

In [454]:
s=np.multiply(x,y)

In [455]:
s

array([[ 605,  792],
       [1485, 1408]])

In [456]:
l=np.subtract(x,y)

In [457]:
l

array([[-44, -54],
       [-84, -72]])

In [458]:
l1=np.divide(x,y)

In [459]:
l1

array([[0.2       , 0.18181818],
       [0.15151515, 0.18181818]])

In [462]:
l2=np.power(x,2)
l2

array([[121, 144],
       [225, 256]], dtype=int32)

# CONDITIONAL STATEMENTS

In [467]:
import numpy as np

In [468]:
x=np.array([i for i in range(10)])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [469]:
np.where(x%2==0,'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [476]:
conditionlist=[x<5,x>5]
choicelist=[x**2,x**3]

In [477]:
np.select(conditionlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

# Mathematical & Statstical Functions

In [478]:
ar=np.array([[4,3,2],[10,0,9],[7,74,89]])
ar

array([[ 4,  3,  2],
       [10,  0,  9],
       [ 7, 74, 89]])

In [479]:
np.amin(ar)

0

In [480]:
np.amin(ar,axis=0)

array([4, 0, 2])

In [481]:
np.amin(ar,axis=1)

array([2, 0, 7])

In [482]:
np.amax(ar)

89

In [483]:
np.amax(ar,axis=1)

array([ 4, 10, 89])

In [484]:
np.median(ar)

7.0

In [485]:
np.mean(ar)

22.0

In [486]:
np.std(ar)

32.145502536643185

In [487]:
np.var(ar)

1033.3333333333333

In [488]:
np.percentile(ar,50)

7.0

In [489]:
deg=np.array([0,30,45,60,90])
deg

array([ 0, 30, 45, 60, 90])

In [490]:
np.sin(deg+np.pi/100)

array([ 0.03141076, -0.98269893,  0.86698442, -0.33457623,  0.8794812 ])

In [491]:
np.cos(deg+np.pi/100)

array([ 0.99950656,  0.18521016,  0.49833525, -0.94236869, -0.47593363])

In [492]:
np.tan(deg+np.pi/100)

array([ 0.03142627, -5.3058587 ,  1.73976138,  0.35503751, -1.84790722])

In [493]:
#inverse trigonometric fuctions
#arcsin
#arccos
#arctan

In [494]:
ar1=np.array([0.1,0.8,-2,2,-10,12.22])

In [495]:
np.floor(ar1)

array([  0.,   0.,  -2.,   2., -10.,  12.])

In [496]:
np.ceil(ar1)

array([  1.,   1.,  -2.,   2., -10.,  13.])

# 1, 2, 3 Dimensional arrays

In [502]:
ar1d=np.array([1,2,3,4,5,6])
ar2d=np.array([[1,2,3],[4,5,6]])
ar3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,5,7]]])

In [504]:
ar1d[0]

1

In [505]:
ar1d[1]

2

In [506]:
ar1d[-3]

4

In [507]:
ar1d[-6]

1

In [508]:
ar2d

array([[1, 2, 3],
       [4, 5, 6]])

In [509]:
ar2d[1,0]

4

In [510]:
ar2d[1,-1]

6

In [511]:
ar3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 5, 7]]])

In [512]:
ar3d[0,0,0]

1

In [515]:
ar3d[-2,-2,-3]

1

# Pandas

In [516]:
import pandas as pd

In [523]:
l=[x for x in range(5)]

In [524]:
l

[0, 1, 2, 3, 4]

In [525]:
s=pd.Series(l)

In [526]:
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [527]:
s[3]

3

In [528]:
s=pd.Series(l,index=['a','b','c','d','e'])

In [529]:
s

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [531]:
s['e']

4

In [534]:
s=pd.Series([x for x in range(1,11)])

In [535]:
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [537]:
s.iloc[0]

1

In [538]:
s.iloc[2]

3

In [539]:
s.iat[6]

7

In [540]:
s[5:9]

5    6
6    7
7    8
8    9
dtype: int64

In [542]:
s.where(s%2==0)

0     NaN
1     2.0
2     NaN
3     4.0
4     NaN
5     6.0
6     NaN
7     8.0
8     NaN
9    10.0
dtype: float64

In [546]:
s.where(s%2==0,'Odd Number')

0    Odd Number
1             2
2    Odd Number
3             4
4    Odd Number
5             6
6    Odd Number
7             8
8    Odd Number
9            10
dtype: object

In [547]:
s.where(s%2==0,s**3)

0      1
1      2
2     27
3      4
4    125
5      6
6    343
7      8
8    729
9     10
dtype: int64

In [551]:
s.where(s%2==0,inplace=True)

In [552]:
s.dropna()

1     2.0
3     4.0
5     6.0
7     8.0
9    10.0
dtype: float64

In [553]:
s.fillna('Filled Value')

0    Filled Value
1             2.0
2    Filled Value
3             4.0
4    Filled Value
5             6.0
6    Filled Value
7             8.0
8    Filled Value
9            10.0
dtype: object

### Dataframe in pandas

In [554]:
df=pd.DataFrame()

In [555]:
type(df)

pandas.core.frame.DataFrame

In [557]:
df=pd.read_csv('PandasExample.csv')

In [558]:
df

Name  Age  Gender
0        Nithin   24    Male
1         Manoj   30    Male
2  Shivashankar   44    Male
3        Swathi   18  Female
4   Pareekshith   28    Male

In [559]:
df.head()

Name  Age  Gender
0        Nithin   24    Male
1         Manoj   30    Male
2  Shivashankar   44    Male
3        Swathi   18  Female
4   Pareekshith   28    Male

In [560]:
df.tail()

Name  Age  Gender
0        Nithin   24    Male
1         Manoj   30    Male
2  Shivashankar   44    Male
3        Swathi   18  Female
4   Pareekshith   28    Male

In [561]:
df.head(2)

Name  Age Gender
0  Nithin   24   Male
1   Manoj   30   Male

In [562]:
df.tail(2)

Name  Age  Gender
3       Swathi   18  Female
4  Pareekshith   28    Male

In [563]:
df.iloc[0]

Name      Nithin
Age           24
Gender      Male
Name: 0, dtype: object

In [564]:
df.values

array([['Nithin', 24, 'Male'],
       ['Manoj', 30, 'Male'],
       ['Shivashankar', 44, 'Male'],
       ['Swathi', 18, 'Female'],
       ['Pareekshith', 28, 'Male']], dtype=object)

In [566]:
df=pd.read_csv('PandasExample.csv',chunksize=2)

In [568]:
for chunk in df:
    print(chunk)

     Name  Age Gender
0  Nithin   24   Male
1   Manoj   30   Male
           Name  Age  Gender
2  Shivashankar   44    Male
3        Swathi   18  Female
          Name  Age Gender
4  Pareekshith   28   Male


In [569]:
df=pd.read_csv('PandasExample.csv')

In [570]:
df=df[df['Age']>25]

In [571]:
df

Name  Age Gender
1         Manoj   30   Male
2  Shivashankar   44   Male
4   Pareekshith   28   Male

# Pandas Panel

In [574]:
df=pd.read_csv('HousePrices.csv',parse_dates=True)

In [575]:
df

date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5           0     0          3        1340   
1         9050     2.0           0     4          5        3370   
2        11947     1.0           0     0          4        1930   
3         8030     1.0           0     0          4        1000   
4        10500     1.0           0     0          4        1140   
...        ...     ...         ...   ...        ...         ...   
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated                    street  \
0                 0      1955          2005      18810 Densmore Ave N   
1               280      1921             0           709 W Blaine St   
2                 0      1966             0  26206-26214 143rd Ave SE   
3              1000      1963             0           857 170th Pl NE   
4               800      1976          1992         9105 170th Ave NE   
...             ...       ...           ...                       ...   
4595              0      1954          1979            501 N 143rd St   
4596              0      1983          2009          14855 SE 10th Pl   
4597              0      2009             0          759 Ilwaco Pl NE   
4598           1020      1974             0         5148 S Creston St   
4599              0      1990             0         18717 SE 258th St   

           city  statezip country  
0     Shoreline  WA 98133     USA  
1       Seattle  WA 98119     USA  
2          Kent  WA 98042     USA  
3      Bellevue  WA 98008     USA  
4       Redmond  WA 98052     USA  
...         ...       ...     ...  
4595    Seattle  WA 98133     USA  
4596   Bellevue  WA 98007     USA  
4597     Renton  WA 98059     USA  
4598    Seattle  WA 98178     USA  
4599  Covington  WA 98042     USA  

[4600 rows x 18 columns]

In [577]:
df.set_index(['city','date'],inplace=True)

In [578]:
df

price  bedrooms  bathrooms  sqft_living  \
city      date                                                                  
Shoreline 2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
Seattle   2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
Kent      2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
Bellevue  2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
Redmond   2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                                     ...       ...        ...          ...   
Seattle   2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
Bellevue  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
Renton    2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
Seattle   2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
Covington 2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

                               sqft_lot  floors  waterfront  view  condition  \
city      date                                                                 
Shoreline 2014-05-02 00:00:00      7912     1.5           0     0          3   
Seattle   2014-05-02 00:00:00      9050     2.0           0     4          5   
Kent      2014-05-02 00:00:00     11947     1.0           0     0          4   
Bellevue  2014-05-02 00:00:00      8030     1.0           0     0          4   
Redmond   2014-05-02 00:00:00     10500     1.0           0     0          4   
...                                 ...     ...         ...   ...        ...   
Seattle   2014-07-09 00:00:00      6360     1.0           0     0          4   
Bellevue  2014-07-09 00:00:00      7573     2.0           0     0          3   
Renton    2014-07-09 00:00:00      7014     2.0           0     0          3   
Seattle   2014-07-10 00:00:00      6630     1.0           0     0          3   
Covington 2014-07-10 00:00:00      8102     2.0           0     0          4   

                               sqft_above  sqft_basement  yr_built  \
city      date                                                       
Shoreline 2014-05-02 00:00:00        1340              0      1955   
Seattle   2014-05-02 00:00:00        3370            280      1921   
Kent      2014-05-02 00:00:00        1930              0      1966   
Bellevue  2014-05-02 00:00:00        1000           1000      1963   
Redmond   2014-05-02 00:00:00        1140            800      1976   
...                                   ...            ...       ...   
Seattle   2014-07-09 00:00:00        1510              0      1954   
Bellevue  2014-07-09 00:00:00        1460              0      1983   
Renton    2014-07-09 00:00:00        3010              0      2009   
Seattle   2014-07-10 00:00:00        1070           1020      1974   
Covington 2014-07-10 00:00:00        1490              0      1990   

                               yr_renovated                    street  \
city      date                                                          
Shoreline 2014-05-02 00:00:00          2005      18810 Densmore Ave N   
Seattle   2014-05-02 00:00:00             0           709 W Blaine St   
Kent      2014-05-02 00:00:00             0  26206-26214 143rd Ave SE   
Bellevue  2014-05-02 00:00:00             0           857 170th Pl NE   
Redmond   2014-05-02 00:00:00          1992         9105 170th Ave NE   
...                                     ...                       ...   
Seattle   2014-07-09 00:00:00          1979            501 N 143rd St   
Bellevue  2014-07-09 00:00:00          2009          14855 SE 10th Pl   
Renton    2014-07-09 00:00:00             0          759 Ilwaco Pl NE   
Seattle   2014-07-10 00:00:00             0         5148 S Creston St   
Covington 2014-07-10 00:00:00             0         18717 SE 258th St   

                               statezip country  
city      date                  

In [579]:
df.index

MultiIndex([(   'Shoreline', '2014-05-02 00:00:00'),
            (     'Seattle', '2014-05-02 00:00:00'),
            (        'Kent', '2014-05-02 00:00:00'),
            (    'Bellevue', '2014-05-02 00:00:00'),
            (     'Redmond', '2014-05-02 00:00:00'),
            (     'Seattle', '2014-05-02 00:00:00'),
            (     'Redmond', '2014-05-02 00:00:00'),
            ('Maple Valley', '2014-05-02 00:00:00'),
            (  'North Bend', '2014-05-02 00:00:00'),
            (     'Seattle', '2014-05-02 00:00:00'),
            ...
            (      'Renton', '2014-07-08 00:00:00'),
            (     'Seattle', '2014-07-08 00:00:00'),
            ( 'Federal Way', '2014-07-08 00:00:00'),
            (      'Auburn', '2014-07-08 00:00:00'),
            (        'Kent', '2014-07-09 00:00:00'),
            (     'Seattle', '2014-07-09 00:00:00'),
            (    'Bellevue', '2014-07-09 00:00:00'),
            (      'Renton', '2014-07-09 00:00:00'),
            (     'Seattle', '

In [580]:
df.loc['Seattle']

price  bedrooms  bathrooms  sqft_living  sqft_lot  \
date                                                                            
2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650      9050   
2014-05-02 00:00:00  4.900000e+05       2.0       1.00          880      6380   
2014-05-02 00:00:00  6.400000e+05       4.0       2.00         1520      6200   
2014-05-02 00:00:00  1.400000e+06       4.0       2.50         2920      4000   
2014-05-02 00:00:00  3.650000e+05       3.0       1.00         1090      6435   
...                           ...       ...        ...          ...       ...   
2014-07-07 00:00:00  4.060625e+05       2.0       1.00         1290      4650   
2014-07-07 00:00:00  4.868950e+05       3.0       1.00         1890      3330   
2014-07-08 00:00:00  3.961667e+05       3.0       1.75         1880      5752   
2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510      6360   
2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090      6630   

                     floors  waterfront  view  condition  sqft_above  \
date                                                                   
2014-05-02 00:00:00     2.0           0     4          5        3370   
2014-05-02 00:00:00     1.0           0     0          3         880   
2014-05-02 00:00:00     1.5           0     0          3        1520   
2014-05-02 00:00:00     1.5           0     0          5        1910   
2014-05-02 00:00:00     1.0           0     0          4        1090   
...                     ...         ...   ...        ...         ...   
2014-07-07 00:00:00     1.0           0     0          4        1290   
2014-07-07 00:00:00     1.5           0     0          4        1390   
2014-07-08 00:00:00     1.0           0     0          4         940   
2014-07-09 00:00:00     1.0           0     0          4        1510   
2014-07-10 00:00:00     1.0           0     0          3        1070   

                     sqft_basement  yr_built  yr_renovated  \
date                                                         
2014-05-02 00:00:00            280      1921             0   
2014-05-02 00:00:00              0      1938          1994   
2014-05-02 00:00:00              0      1945          2010   
2014-05-02 00:00:00           1010      1909          1988   
2014-05-02 00:00:00              0      1955          2009   
...                            ...       ...           ...   
2014-07-07 00:00:00              0      1906          1990   
2014-07-07 00:00:00            500      1901             0   
2014-07-08 00:00:00            940      1945             0   
2014-07-09 00:00:00              0      1954          1979   
2014-07-10 00:00:00           1020      1974             0   

                                    street  statezip country  
date                                                          
2014-05-02 00:00:00        709 W Blaine St  WA 98119     USA  
2014-05-02 00:00:00         522 NE 88th St  WA 98115     USA  
2014-05-02 00:00:00       6811 55th Ave NE  WA 98115     USA  
2014-05-02 00:00:00  3838-4098 44th Ave NE  WA 98105     USA  
2014-05-02 00:00:00    2504 SW Portland Ct  WA 98106     USA  
...                                    ...       ...     ...  
2014-07-07 00:00:00         312 NE 81st St  WA 98115     USA  
2014-07-07 00:00:00      4324 Dayton Ave N  WA 98103     USA  
2014-07-08 00:00:00     3529 SW Webster St  WA 98126     USA  
2014-07-09 00:00:00         501 N 143rd St  WA 98133     USA  
2014-07-10 00:00:00      5148 S Creston St  WA 98178     USA  

[1573 rows x 16 columns]

In [581]:
df.loc['Seattle'].loc['2014-05-02 00:00:00']

price  bedrooms  bathrooms  sqft_living  sqft_lot  \
date                                                                         
2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2014-05-02 00:00:00   490000.0       2.0       1.00          880      6380   
2014-05-02 00:00:00   640000.0       4.0       2.00         1520      6200   
2014-05-02 00:00:00  1400000.0       4.0       2.50         2920      4000   
2014-05-02 00:00:00   365000.0       3.0       1.00         1090      6435   
2014-05-02 00:00:00  1200000.0       5.0       2.75         2910      9480   
2014-05-02 00:00:00   750000.0       3.0       1.75         2240     10578   
2014-05-02 00:00:00   626000.0       3.0       2.25         1750      1572   
2014-05-02 00:00:00   495000.0       4.0       1.75         1600      6380   
2014-05-02 00:00:00   615000.0       3.0       1.75         2360      7291   
2014-05-02 00:00:00   790000.0       3.0       2.50         2600      4750   
2014-05-02 00:00:00   650000.0       4.0       2.00         1820      5000   
2014-05-02 00:00:00   440000.0       2.0       1.00          800      4850   
2014-05-02 00:00:00   750000.0       3.0       2.50         2390      6550   
2014-05-02 00:00:00   439950.0       3.0       2.50         1770      2875   
2014-05-02 00:00:00   235000.0       2.0       1.00         1210      9400   
2014-05-02 00:00:00   445700.0       3.0       2.50         1270      1180   
2014-05-02 00:00:00   805000.0       3.0       2.00         2710      4500   
2014-05-02 00:00:00   385000.0       3.0       3.25         1320      1327   
2014-05-02 00:00:00   295000.0       2.0       2.50         1630      1368   
2014-05-02 00:00:00   436110.0       3.0       2.50         1770      1235   

                     floors  waterfront  view  condition  sqft_above  \
date                                                                   
2014-05-02 00:00:00     2.0           0     4          5        3370   
2014-05-02 00:00:00     1.0           0     0          3         880   
2014-05-02 00:00:00     1.5           0     0          3        1520   
2014-05-02 00:00:00     1.5           0     0          5        1910   
2014-05-02 00:00:00     1.0           0     0          4        1090   
2014-05-02 00:00:00     1.5           0     0          3        2910   
2014-05-02 00:00:00     2.0           0     0          5        1550   
2014-05-02 00:00:00     2.5           0     0          3        1470   
2014-05-02 00:00:00     1.0           0     0          3        1130   
2014-05-02 00:00:00     1.0           0     0          4        1360   
2014-05-02 00:00:00     1.0           0     0          4        1700   
2014-05-02 00:00:00     1.5           0     1          3        1640   
2014-05-02 00:00:00     1.0           0     0          4         800   
2014-05-02 00:00:00     1.0           0     2          4        1440   
2014-05-02 00:00:00     2.0           0     0          3        1770   
2014-05-02 00:00:00     1.0           0     0          2        1210   
2014-05-02 00:00:00     3.0           0     0          3        1270   
2014-05-02 00:00:00     1.5           0     0          4        1880   
2014-05-02 00:00:00     2.0           0     0          3        1040   
2014-05-02 00:00:00     2.0           0     0          3        1280   
2014-05-02 00:00:00     3.0           0     0          3        1600   

                     sqft_basement  yr_built  yr_renovated  \
date                                                         
2014-05-02 00:00:00            280      1921             0   
2014-05-02 00:00:00              0      1938          1994   
2014-05-02 00:00:00              0      1945          2010   
2014-05-02 00:00:00           1010      1909          1988   
2014-05-02 00:00:00              0      1955          2009   
2014-05-02 00:00:00              0      1939          1969   
2014-05-02 00:00:00            690      1923             0   
2014-05-02 00:0