In [2]:
885556/5555656

0.15939719809865838

In [3]:
55889*65566

3664418174

__Python__

# My First Program 

In [4]:
#variable 

In [5]:
x=10

In [6]:
print(x)

10


In [7]:
type(x)

int

In [8]:
y=10.5

In [9]:
print(y)

10.5


In [10]:
type(y)

float

In [11]:
z='cc'

In [12]:
print(z)

cc


In [13]:
type(z)

str

In [14]:
z1="cc's"

In [15]:
z1

"cc's"

In [16]:
#list

In [17]:
l1=[10,20,30,'xx']

In [18]:
l1

[10, 20, 30, 'xx']

In [19]:
type(l1)

list

In [20]:
l1[1]

20

In [21]:
l1[1]=15

In [22]:
l1

[10, 15, 30, 'xx']

In [23]:
l1[-2]

30

In [24]:
#slicing
l1[1:2]

[15]

In [25]:
l1[1:3]

[15, 30]

In [26]:
l1.append(40)

In [27]:
l1

[10, 15, 30, 'xx', 40]

In [28]:
l1.append([50,60])

In [29]:
l1

[10, 15, 30, 'xx', 40, [50, 60]]

In [30]:
l1.extend([70,80])

In [31]:
l1

[10, 15, 30, 'xx', 40, [50, 60], 70, 80]

In [32]:
l1.insert(2,'yy')

In [33]:
l1

[10, 15, 'yy', 30, 'xx', 40, [50, 60], 70, 80]

In [34]:
l1.pop(2)

'yy'

In [35]:
l1

[10, 15, 30, 'xx', 40, [50, 60], 70, 80]

In [36]:
l1.insert(2,[5,6,7])

In [37]:
l1

[10, 15, [5, 6, 7], 30, 'xx', 40, [50, 60], 70, 80]

In [38]:
l1.remove(40)

In [39]:
l1

[10, 15, [5, 6, 7], 30, 'xx', [50, 60], 70, 80]

In [40]:
#dictionary 

In [41]:
dict1={'xx':10,'yy':20,'zz':30}

In [3]:
dict1

{'xx': 10, 'yy': 20, 'zz': 30}

In [4]:
type(dict1)

dict

In [5]:
dict2={'10':'xx','20':30}

In [6]:
dict2

{'10': 'xx', '20': 30}

In [8]:
dict1.keys()

dict_keys(['xx', 'yy', 'zz'])

In [9]:
dict1['xx']

10

In [10]:
dict1['xx']=5

In [11]:
dict1

{'xx': 5, 'yy': 20, 'zz': 30}

In [12]:
dict1.values()

dict_values([5, 20, 30])

In [13]:
dict1.update({'ll':50,'kk':40})

In [14]:
dict1

{'xx': 5, 'yy': 20, 'zz': 30, 'll': 50, 'kk': 40}

In [15]:
dict1.clear()

In [16]:
dict1

{}

In [17]:
dict3={'xx':10,'yy':20,'zz':{'ll':40,'kk':50}}

In [18]:
dict3

{'xx': 10, 'yy': 20, 'zz': {'ll': 40, 'kk': 50}}

In [20]:
dict2.pop('10')

'xx'

In [21]:
dict3

{'xx': 10, 'yy': 20, 'zz': {'ll': 40, 'kk': 50}}

In [22]:
dict3['zz']

{'ll': 40, 'kk': 50}

In [23]:
dict3['zz']['ll']

40

In [24]:
dict2

{'20': 30}

In [25]:
#tuple

In [26]:
t=(10,20,30,40,'xx')

In [27]:
t

(10, 20, 30, 40, 'xx')

In [28]:
type(t)

tuple

In [29]:
t[1]

20

In [30]:
t[1]=5

TypeError: 'tuple' object does not support item assignment

In [31]:
t.append(60)

AttributeError: 'tuple' object has no attribute 'append'

In [32]:
len(t)

5

In [34]:
t1=(100,10,20,8,50)

In [35]:
max(t1)

100

In [36]:
#set

In [37]:
s1=set(t1)

In [38]:
s1

{8, 10, 20, 50, 100}

In [39]:
type(s1)

set

In [40]:
s1.add(88)

In [41]:
s1

{8, 10, 20, 50, 88, 100}

In [42]:
t2=tuple(s1)

In [43]:
t2

(100, 8, 10, 50, 20, 88)

In [44]:
type(t2)

tuple

In [56]:
s1=set(['xx','yy','zz'])
s2=set(['xx','yy','zz','ll'])

In [57]:
s1

{'xx', 'yy', 'zz'}

In [47]:
s2

{'ll', 'xx', 'yy', 'zz'}

In [48]:
s1.intersection(s2)

{'xx', 'yy', 'zz'}

In [49]:
s1.union(s2)

{'ll', 'xx', 'yy', 'zz'}

In [50]:
s1.difference(s2)

set()

In [51]:
s2.difference(s1)

{'ll'}

In [52]:
s1.issubset(s2)

True

In [53]:
s2.issuperset(s1)

True

In [58]:
#numpy

In [59]:
import numpy as np

In [60]:
arr1=np.array([3,33,333])#rank 1 

In [61]:
arr1

array([  3,  33, 333])

In [62]:
arr1[0]

3

In [63]:
arr1[0]=5

In [64]:
arr1

array([  5,  33, 333])

In [65]:
arr2=np.array([[5,55,555],[6,66,666]])#rank 2 array 

In [66]:
arr2

array([[  5,  55, 555],
       [  6,  66, 666]])

In [67]:
arr2[0]

array([  5,  55, 555])

In [68]:
arr2[0][1]

55

In [69]:
a1=np.zeros([2,2])

In [70]:
a1

array([[0., 0.],
       [0., 0.]])

In [71]:
a2=np.ones([2,2])

In [72]:
a2

array([[1., 1.],
       [1., 1.]])

In [73]:
a3=np.full([2,2],9)

In [74]:
a3

array([[9, 9],
       [9, 9]])

In [75]:
a4=np.eye(3,3)

In [76]:
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
a5=np.eye(2,2)

In [78]:
a5


array([[1., 0.],
       [0., 1.]])

In [79]:
a6=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [80]:
a6

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [81]:
a6.shape

(3, 3)

In [84]:
a6[1:3]

array([[40, 50, 60],
       [70, 80, 90]])

In [85]:
a6[0:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [86]:
a6[2:,]#return rows

array([[70, 80, 90]])

In [87]:
a6[:,2]#return cols 

array([30, 60, 90])

In [88]:
a7=np.array([[11,12],[15,16],[20,25]])

In [89]:
a7

array([[11, 12],
       [15, 16],
       [20, 25]])

In [90]:
filter1=(a7>15)

In [91]:
filter1

array([[False, False],
       [False,  True],
       [ True,  True]])

In [93]:
a7[filter1]

array([16, 20, 25])

In [94]:
ex2=np.array([11,12],dtype=np.float64)

In [95]:
ex2

array([11., 12.])

In [96]:
ex3=np.array([11.5,12.5],dtype=np.int64)

In [97]:
ex3

array([11, 12], dtype=int64)

In [98]:
x=np.array([[11,12],[15,16]])
y=np.array([[100,200],[110,115]])

In [99]:
z=x+y

In [100]:
z

array([[111, 212],
       [125, 131]])

In [101]:
z=np.add(x,y)

In [102]:
z

array([[111, 212],
       [125, 131]])

In [103]:
z1=np.subtract(x,y)

In [104]:
z1

array([[ -89, -188],
       [ -95,  -99]])

In [105]:
z2=np.multiply(x,y)

In [106]:
z2

array([[1100, 2400],
       [1650, 1840]])

In [107]:
z3=np.divide(x,y)

In [108]:
z3

array([[0.11      , 0.06      ],
       [0.13636364, 0.13913043]])